Adds repo creation to ghd
Use some/repo+ to create repos, if they don't already exist.

diff --git a/ghd b/ghd
--- a/ghd
+++ b/ghd
@@ -215,6 +215,49 @@ function _ghd_run() {
     return 1
   }
 
+  function maybe_create_repo() { # location_root repo_name
+    local location_root="$1"
+    local repo_name="$2"
+    local repo_url
+
+    if [[ -z "$repo_name" ]]; then
+      return 1
+    fi
+
+    if [[ "$repo_name" == "/" ]]; then
+      return 1
+    fi
+
+    if [[ "$repo_name" != *"/"* ]]; then
+      return 1
+    fi
+
+    # Assume repo_name is a user/org format
+    repo_url="$(get_repo_url "$repo_name")"
+
+    if git ls-remote "$repo_url" >/dev/null 2>&1; then
+      echo "Cannot create repo - already exists on github: $repo_name"
+      return 2
+    fi
+
+    git init "$location_root/$repo_name"
+    cd "$location_root/$repo_name"
+
+    if ! gh auth status > /dev/null 2>&1; then
+      git remote add origin "$repo_url"
+    else
+      gh repo create "$repo_name" --private --source .
+      result=$?
+      if [[ $result -ne 0 ]]; then
+        cd -
+        rm -rf "$location_root/$repo_name"
+        return 3
+      fi
+    fi
+
+    return 0
+  }
+
   function find_target() { # repo_name
     local repo_name="$1"
 
@@ -289,6 +332,18 @@ function _ghd_run() {
   if [[ "$repo_name" == *"@"* ]]; then
     branch=$(echo $repo_name | cut -f2 -d@)
     repo_name=$(echo $repo_name | cut -f1 -d@)
+  fi
+
+  if [[ $is_plus -eq 1 ]]; then
+    maybe_create_repo "$location_root" "$repo_name"
+    result=$?
+    if [[ $result -eq 0 ]]; then
+      # This was a create repo request, and we've handled it.
+      return 0
+    elif [[ $result -ne 1 ]]; then
+      # Something really bad happened.
+      return $result
+    fi
   fi
 
   if [[ -n "$branch" ]] && [[ -z "$repo_name" ]]; then
